Cypress tests
vtex-apps/taxjar pull request #60
Opened 2022-09-29 09:58 UTC by shashidhar85

2022-09-29 11:30 UTC, Syed-Vtex commented on cypress/integration/2.1-graphql_testcases.spec.js
> +import {
@sumanraj123

2022-09-30 11:22 UTC, Syed-Vtex requested changes

2022-09-30 11:23 UTC, Syed-Vtex commented on cypress/integration/2.1-graphql_testcases.spec.js
> +  loginViaCookies()
In ticket we have lot of graphql mentioned but here we just have 3
@sumanraj123 
https://vtex-dev.atlassian.net/jira/software/c/projects/ENGINEERS/boards/630?modal=detail&selectedIssue=ENGINEERS-679

2022-09-30 11:23 UTC, Syed-Vtex commented on cypress/support/edition_app_lists.js
> +    app: 'vtex.orders-broadcast',
This you don't need i guess take from common folder

2022-09-30 11:24 UTC, Syed-Vtex commented on cypress/support/graphql.js
> +  // authorizationHeader,
Remove commented code

2022-09-30 11:25 UTC, Syed-Vtex commented on cypress/support/index.js
> +Cypress.on('uncaught:exception', (_, __) => {
do we need this

2022-10-03 10:08 UTC, sumanraj123 commented on cypress/integration/2.1-graphql_testcases.spec.js
> +  loginViaCookies()
added two more graphql testcases
@Syed-Vtex

2022-10-03 10:09 UTC, sumanraj123 commented on cypress/integration/2.1-graphql_testcases.spec.js
> +describe('Affirm GraphQL Validation', () => {
updated the title with taxjar

2022-10-07 09:47 UTC, shashidhar85 commented on cypress/support/index.js
> +Cypress.on('uncaught:exception', (_, __) => {
yes

2022-10-10 06:17 UTC, Syed-Vtex commented on cypress/support/commands.js
> +Cypress.Commands.add('orderTaxApi', (requestPayload, tax) => {
In common, api_commands.js we have orderTaxApi commands 
@shashidhar85 Can you please try using it

2022-10-10 06:39 UTC, Syed-Vtex requested changes

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/transaction_api.js
> +  { prefix, refundedAmount },
@saravananvenkatesan address this when you complete verify transaction in taxjar

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/testcases.js
> +          if (status === 'invoiced') {
@sumanraj123 add validations here or if you don't need this please remove

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +  restAndGraphqlAPI: {
We should not have two different outputvalidation file
Merge them into one and remove properties which we don't use
@sumanraj123 @shashidhar85

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/index.js
> +Cypress.on('uncaught:exception', (_, __) => {
Is taxJar throwing any errors
?

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/graphql_testcase.js
> +  const APP = `${APP_NAME}@2.x`
use *.x instead of 2.x

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/common.js
> +  before(() => {
Since it is used in only one file
You can have it inside the testcase rather than here

Function name should be 
loginAsExemptionUser

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/common.js
> +      loginAsUser(vtex.email, vtex.password)
instead of email
Use syedEmail
So, that we will know whose email is been used
This will help us in debugging failures

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/support/api_testcase.js
> +          // Pickup points created in E2E tests should start with text "pickup example"
Please update the comment

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/wipe.spec.js
> +  configureTaxConfigurationInOrderForm()
We can drop configureTaxConfigurationInOrderForm, configureTargetWorkspace, configureTargetWorkspace

Now cy-runner will handle them for us
You need to put below code in cy-runner

# The nex configuration avoid apps that need account
  # level resources from running in parallel
  reserveAccount:
    enabled: true
    setup:
      - orderForm
      - vtex.orders-broadcast@0.x
      
      
      Reference: https://github.com/vtex/avalara/pull/165/files
      
      @shashidhar85 @saravananvenkatesan @sumanraj123 
      here after follow above approach

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/post-setup.spec.js
> +  configureTaxConfigurationInOrderForm(name)
Same goes here refer wipe

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.8-partialRefund.spec.js
> +  // Request partial refund for the ordered product added in 2.3-multiProduct.spec.js
Please update the comments 
Comment is written for different app here the filename is different

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.6-discount-product.spec.js
> +    // trackingEnv: shipStationTrackingEnv
@sumanraj123 if you don't need this line then please comment

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.5-promotionalProduct.spec.js
> +    cy.orderProduct()
@sumanraj123 please verify transaction for this testcase

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.4-multi-product.spec.js
> +  // it(`Visit admin endpoint and upload file`, updateRetry(2), () => {
Why this is commented 
@shashidhar85

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.4-multi-product.spec.js
> +      // pickup: true,
Please remove this code 
// pickup: true,

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.4-multi-product.spec.js
> +        .should('have.text', taxWithoutExemption)
@sumanraj123 
Please update the variable name as discussed
We should use taxWithoutExemption as name only when we are verifying taxWithoutExemption

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.2-single-product.spec.js
> +  loginAsExcemptionUser()
Correct this functionName
loginAsExemptionUser

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.2-single-product.spec.js
> +describe('Testing Product tax and total amounts', () => {
Update the title to match your actions

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.2-single-product.spec.js
> +    // trackingEnv: shipStationTrackingEnv
@sumanraj123 Remove this commented code from all testcase    // trackingEnv: shipStationTrackingEnv

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.3-discount-shipping.spec.js
> +    saveOrderId(orderIdEnv)
@sumanraj123 Here transaction is not verified please do

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.5-promotionalProduct.spec.js
> +const { orderIdEnv } = promotionalProductEnvs
@saravananvenkatesan 
Add order TAX api testcase for promotionaproduct

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/integration/2.6-discount-product.spec.js
> +describe('Discount Product Testcase', () => {
Add order TAX api testcase for discountProduct

2022-10-10 06:39 UTC, Syed-Vtex commented on cypress/fixtures/multiProduct.json
> +  "items": [
@sumanraj123 Add external testcase

2022-10-10 06:39 UTC, Syed-Vtex commented on cy-runner.yml
> +    deployCli:
We don't need deployCli and twillio anymore
It is deprecated

deployCli:
      enabled: true
      git: https://github.com/vtex/toolbelt.git
      branch: qe/cypress
  twilio:
    enabled: true

2022-10-10 06:39 UTC, Syed-Vtex commented on cy-runner.yml
> +    testing: true
@thyarles has dropped testing:true in avalara
@Syed-Vtex is following on this

2022-10-10 06:39 UTC, Syed-Vtex commented on cy-runner.yml
> +    projectId: ''
@Syed-Vtex will share the projectId

2022-10-10 06:39 UTC, Syed-Vtex commented on cy-runner.yml
> +    sorry: false
This also we can drop now

2022-10-10 06:39 UTC, Syed-Vtex commented on cy-runner.yml
> +    logOutput:
@shashidhar85 @sumanraj123 @saravananvenkatesan 
Please compare this yml file with avalara yml file
https://github.com/vtex/avalara/pull/165/files

You will know what is been deprecated will be helpful for you in future apps

2022-10-10 06:40 UTC, Syed-Vtex commented on cypress/integration/2.2-single-product.spec.js
> +  verifyOrderStatus({
@sumanraj123 there is possibility that sonarcloud might report that you are duplicating code on below lines

So, please move this to function where it can be used by all UI testcases

2022-10-10 06:46 UTC, Syed-Vtex commented on cy-runner.yml
> +    projectId: ''
@shashidhar85 
projectId -> 1ae2jq

2022-10-10 09:10 UTC, shashidhar85 commented on cypress/support/index.js
> +Cypress.on('uncaught:exception', (_, __) => {
no

2022-10-10 13:41 UTC, Syed-Vtex commented on cy-runner.yml
> +    testing: true
@shashidhar85 pls drop 
testing:true

2022-10-11 06:46 UTC, Syed-Vtex requested changes

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/integration/2.7-discount-product.spec.js
> +  orderTaxAPITestCase('discountProduct', tax)
discountProduct json file is not there in fixtures
@shashidhar85 pls check

2022-10-11 06:46 UTC, Syed-Vtex commented on cy-runner.yml
> +    stopOnFail: true
Drop stopOnFail option here
Because on graphql / api failure we need to create ticket

2022-10-11 06:46 UTC, Syed-Vtex commented on cy-runner.yml
> +      - cypress/integration/2.3-discount-shipping.spec.js
Add dependency or else 
Github will run below strategy in parallel
verify_tax_without_nexus_enable_testcases
verify_tax_with_nexus_enable_testcases

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/integration/2.10-externalseller.spec.js
> +  //   orderTaxAPITestCase('externalSeller',externalSeller.tax)
@sumanraj123 why it is disabled + put external seller in 2.8 
2.9 fullrefund 2.10 partialrefund

cc - @shashidhar85

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/integration/2.10-externalseller.spec.js
> +  //   orderTaxAPITestCase('externalSeller',externalSeller.tax)
Order tax api should be called separately for internal and external sale

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/integration/2.5-discount-shipping.spec.js
> +const { prefix, postalCode, productName, productQuantity, tax, totalAmount } =
@saravananvenkatesan Run prettier for this

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/integration/2.7-discount-product.spec.js
> +    // trackingEnv: shipStationTrackingEnv
remove commented code

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/integration/post-setup.spec.js
> +    isLive: false,
@shashidhar85 set isLive to true

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/index.js
> +Cypress.on('uncaught:exception', (_, __) => {
Then you should not have this uncaught exception

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/integration/2.2-rest-apis.spec.js
> +  orderTax('singleProduct')
@shashidhar85 Drop this orderTax here
Because, we already have in UI testcase

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +    taxWithoutExemption: '$ 82.60',
Why we are having tax and taxWithout Exemption here
tax and taxWithoutExemption is only applicable for singleProduct
So, drop taxWithoutExemption from multiproduct

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +    // tax:''
remove commented code

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/api_testcase.js
> +export function orderTax(fixtureName) {
Drop this function

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/apis.js
> +  orderTaxHandler: (baseUrl) => {
Drop this orderTaxHandler

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/graphql.js
> +export function configureTargetWorkspace(app, version, workspace = 'master') {
Drop configureTargetWorkspace and orderForm
Because now it is been handled from cy-runner

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +    // singleProduct, taxExemption, vatNumber,multiProduct,refund,externalSeller uses below product
drop this comment

2022-10-11 06:46 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +  orderProduct: {
are we using this property orderProduct

2022-10-11 11:25 UTC, Syed-Vtex commented on cypress/integration/2.10-externalseller.spec.js
> +  it(`${prefix} - Pay with digital river master card credit card option`, () => {
@sumanraj123 change title

2022-10-11 11:25 UTC, Syed-Vtex commented on cypress/integration/2.10-externalseller.spec.js
> +    sendInvoiceTestCase({
@sumanraj123 verify transaction for extenalSeller

2022-10-12 06:24 UTC, Syed-Vtex commented on cypress/integration/2.9-partialRefund.spec.js
> +describe('Testing Digital River transaction API for partial refund', () => {
@sumanraj123 Fix 1 code smells and duplications

2022-10-12 07:22 UTC, sumanraj123 commented on cypress/integration/2.8-fullRefund-transaction.spec.js
> +describe('Testing Digital River transaction API for full refund', () => {
@Syed-Vtex  fixed the title

2022-10-12 12:43 UTC, Syed-Vtex requested changes

2022-10-12 12:43 UTC, Syed-Vtex commented on cy-runner.yml
> +        - cypress/integration/2.3-single-product.spec.js
@shashidhar85 Put dependency here with 2.1 and 2.2

2022-10-12 12:43 UTC, Syed-Vtex commented on cy-runner.yml
> +      - cypress/integration/2.8-externalseller.spec.js
Put dependency here with 2.3

2022-10-12 12:43 UTC, Syed-Vtex commented on cy-runner.yml
> +      - cypress/integration/2.5-discount-shipping.spec.js
Put dependency here with 2.4,2.6,2.7,2.8

2022-10-12 13:45 UTC, sumanraj123 commented on cypress/integration/2.9-partialRefund.spec.js
> +describe('Testing Digital River transaction API for partial refund', () => {
@Syed-Vtex  fixed the title and one code smell also one code smell is expected in graphql testcase where we added one comment there

2022-10-13 09:25 UTC, Syed-Vtex requested changes

2022-10-13 09:25 UTC, Syed-Vtex commented on cypress/support/outputvalidation.js
> +    OrderId: '1265150518614-01',
If you are using this in payload 
Then @saravananvenkatesan it should be dynamic 
Because order id will not be same all the time

2022-10-13 09:28 UTC, Syed-Vtex commented on cypress/integration/2.7-discount-product.spec.js
> +describe('Discount Product Testcase', () => {
Use like this for consistent
describe(`${prefix} Scenarios`, () => {

2022-10-13 09:29 UTC, Syed-Vtex commented on cypress/integration/wipe.spec.js
> +  testSetup(false)
@shashidhar85 We should not use testSetup
In future we will drop them 

So, please use loginViaCookies here after

2022-10-13 09:29 UTC, Syed-Vtex commented on cypress/integration/wipe.spec.js
> +  testSetup(false)
cc - @saravananvenkatesan @sumanraj123

2022-10-13 09:30 UTC, Syed-Vtex commented on cypress/integration/2.9-fullRefund-transaction.spec.js
> +
loginViaCookies()
is missing here

@sumanraj123

2022-10-13 10:18 UTC, sumanraj123 commented on cypress/integration/2.9-fullRefund-transaction.spec.js
> +
added @Syed-Vtex

2022-10-13 10:19 UTC, sumanraj123 commented on cypress/integration/2.7-discount-product.spec.js
> +describe('Discount Product Testcase', () => {
changed in every places @Syed-Vtex

2022-10-13 10:19 UTC, sumanraj123 commented on cypress/integration/2.9-fullRefund-transaction.spec.js
> +    getRefundPayload
@Syed-Vtex  implemented in both

2022-10-13 10:20 UTC, sumanraj123 commented on cypress/integration/2.9-fullRefund-transaction.spec.js
> +describe('Testing Digital River transaction API for full refund', () => {
@Syed-Vtex this is done ,please have a look

2022-10-13 10:20 UTC, sumanraj123 commented on cypress/integration/2.10-partialRefund.spec.js
> +describe('Testing Digital River transaction API for partial refund', () => {
fixed @Syed-Vtex

2022-10-13 11:37 UTC, Syed-Vtex commented on .github/workflows/qe-pull-request-target.yml
> +      cypress: true
Enable cypress to true in one more workflow file - **qe-pull-request.yml**

2022-10-13 11:59 UTC, Syed-Vtex approved these changes
LGTM

2022-10-13 12:55 UTC, merged